package com.s6.tk_empty;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean a;

	public Person() {
	}

	public java.lang.Boolean getA() {
		return this.a;
	}

	public void setA(java.lang.Boolean a) {
		this.a = a;
	}

	public Person(java.lang.Boolean a) {
		this.a = a;
	}

}